services:
  postgres:
    image: postgres:16
    container_name: sky0cloud-postgres
    restart: unless-stopped
    shm_size: 256mb
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: "Sky0CloudStrongDBPass"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - matrix_network
    ports:
      - "8443:8443"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse_user -d synapse"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: sky0cloud-redis
    restart: unless-stopped
    networks:
      - matrix_network

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: sky0cloud-synapse
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    volumes:
      - ./data/synapse:/data
    networks:
      - matrix_network

  element-web:
    image: vectorim/element-web:latest
    container_name: sky0cloud-element-web
    restart: unless-stopped
    volumes:
      - ./data/element/config.json:/app/config.json
    networks:
      - matrix_network

  synapse-admin:
    image: ghcr.io/etkecc/synapse-admin:latest
    container_name: sky0cloud-synapse-admin
    restart: unless-stopped
    networks:
      - matrix_network

  coturn:
    image: coturn/coturn:latest
    container_name: sky0cloud-turn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/coturn/turnserver.conf:/etc/coturn/turnserver.conf

  caddy:
    image: caddy:2
    container_name: sky0cloud-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/caddy_config:/config
    networks:
      - matrix_network

networks:
  matrix_network:
    driver: bridge

volumes:
  caddy_data:
