tunnel: eyJhIjoiMTk5MDdjNDM5NmRkNTc0MTAxMjY2ODE4YTg5OTkwMzIiLCJ0IjoiMGEzNzA1NzktOTdkMi00NTI5LWFkZDMtMjU3MWRlMTgwM2JjIiwicyI6IlpHTTFNamhoTXpNdE1tRTFNQzAwTldKaExUZzRZamt0T0dZeFl6UmhNMlJoWlRZdyJ9
credentials-file: /etc/cloudflared/eyJhIjoiMTk5MDdjNDM5NmRkNTc0MTAxMjY2ODE4YTg5OTkwMzIiLCJ0IjoiMGEzNzA1NzktOTdkMi00NTI5LWFkZDMtMjU3MWRlMTgwM2JjIiwicyI6IlpHTTFNamhoTXpNdE1tRTFNQzAwTldKaExUZzRZamt0T0dZeFl6UmhNMlJoWlRZdyJ9.json

ingress:
  - hostname: sky0cloud.dpdns.org
    service: http://caddy:80
  - hostname: matrix.sky0cloud.dpdns.org
    service: http://caddy:80
  - service: http_status:404
