tunnel: 0a370579-97d2-4529-add3-2571de1803bc
credentials-file: /etc/cloudflared/0a370579-97d2-4529-add3-2571de1803bc.json

ingress:
  - hostname: sky0cloud.dpdns.org
    service: http://caddy:80

  - hostname: matrix.sky0cloud.dpdns.org
    service: http://caddy:80

  - service: http_status:404
