tunnel: YOUR_TUNNEL_ID
credentials-file: /etc/cloudflared/YOUR_TUNNEL_ID.json

ingress:
  - hostname: sky0cloud.dpdns.org
    service: http://caddy:80
  - hostname: matrix.sky0cloud.dpdns.org
    service: http://caddy:80
  - service: http_status:404
